### ISSUE TITLE
@Published properties playground "viewDidLoad" not called.

### ISSUE THREAD

**Issue by dkulundzic** [AvdLee/CombineSwiftPlayground#10]
Hey there! 

The playground section titled **@Published properties** has an issue where `viewDidLoad`'s not called at all - due to `FormViewController`'s view not being accessed at any time. As a consequence, the subscription's not set-up and the example does not work.

This can be easily solved by adding `formViewController.loadViewIfNeeded()` after `let formViewController = FormViewController(nibName: nil, bundle: nil)`.

**Comment by AvdLee** [comment]
This should be fixed now!
