### ISSUE TITLE
Publishers.Just seems to have vanished from Beta 3

### ISSUE THREAD

**Issue by dirk68-work** [AvdLee/CombineSwiftPlayground#3]
`Publishers.Just` seems to have been removed from Beta 3 and even the corresponding [developer docs](https://developer.apple.com/documentation/combine/publishers/just) are missing.

**Comment by ShurupuS** [comment]
@dirk68-fu it just moved from `Publishers`, now you just have to call it `Just(28)` for example, anyway  @AvdLee resolved this in `feature/beta_3` branch.
